lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "filelock"
version = "3.20.0"

[[packages.wheels]]
name = "filelock-3.20.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/76/91/7216b27286936c16f5b4d0c530087e4a54eead683e6b0b73dd0c64844af6/filelock-3.20.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "339b4732ffda5cd79b13f4e2711a31b0365ce445d95d243bb996273d072546a2"

[[packages]]
name = "fsspec"
version = "2025.9.0"

[[packages.wheels]]
name = "fsspec-2025.9.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/47/71/70db47e4f6ce3e5c37a607355f80da8860a33226be640226ac52cb05ef2e/fsspec-2025.9.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "530dc2a2af60a414a832059574df4a6e10cce927f6f4a78209390fe38955cfb7"

[[packages]]
name = "jinja2"
version = "3.1.6"

[[packages.wheels]]
name = "jinja2-3.1.6-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "85ece4451f492d0c13c5dd7c13a64681a86afae63a5f347908daf103ce6d2f67"

[[packages]]
name = "markupsafe"
version = "3.0.3"

[[packages.wheels]]
name = "markupsafe-3.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/1e/2c/799f4742efc39633a1b54a92eec4082e4f815314869865d876824c257c1e/markupsafe-3.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "3a7e8ae81ae39e62a41ec302f972ba6ae23a5c5396c8e60113e9066ef893da0d"

[[packages]]
name = "mpmath"
version = "1.3.0"

[[packages.wheels]]
name = "mpmath-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a0b2b9fe80bbcd81a6647ff13108738cfb482d481d826cc0e02f5b35e5c88d2c"

[[packages]]
name = "networkx"
version = "3.5"

[[packages.wheels]]
name = "networkx-3.5-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/eb/8d/776adee7bbf76365fdd7f2552710282c79a4ead5d2a46408c9043a2b70ba/networkx-3.5-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "0030d386a9a06dee3565298b4a734b68589749a544acbb6c412dc9e2489ec6ec"

[[packages]]
name = "setuptools"
version = "80.9.0"

[[packages.wheels]]
name = "setuptools-80.9.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a3/dc/17031897dae0efacfea57dfd3a82fdd2a2aeb58e0ff71b77b87e44edc772/setuptools-80.9.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "062d34222ad13e0cc312a4c02d73f059e86a4acbfbdea8f8f76b28c99f306922"

[[packages]]
name = "sympy"
version = "1.14.0"

[[packages.wheels]]
name = "sympy-1.14.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e091cc3e99d2141a0ba2847328f5479b05d94a6635cb96148ccb3f34671bd8f5"

[[packages]]
name = "torch"
version = "2.9.0"

[[packages.wheels]]
name = "torch-2.9.0-cp312-cp312-manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/d1/d3/3985739f3b8e88675127bf70f82b3a48ae083e39cda56305dbd90398fec0/torch-2.9.0-cp312-cp312-manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "e5f7af1dc4c0a7c4a260c2534f41ddaf209714f7c89145e644c44712fbd6b642"

[[packages]]
name = "typing-extensions"
version = "4.15.0"

[[packages.wheels]]
name = "typing_extensions-4.15.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f0fa19c6845758ab08074a0cfa8b7aecb71c999ca73d62883bc25cc018c4e548"
