base_llm: meta-llama/Llama-3.1-8B-Instruct
base_model: null
resume_from_checkpoint: false
wandb_run_id: null
attachment_token: <|reserved_special_token_0|>
tokenizer_type: llama
token_size: 4096

loaders:
  - loader_type: raw-image
    modality_type: image

modalities:
  - model_type: moe_meditron_clip
    image_processor: openai/clip-vit-base-patch32
    hidden_size: 4096
    expert_clip_names:
      - ClosedMeditron/MedExpert-CT
      - ClosedMeditron/MedExpert-MRI
      - ClosedMeditron/MedExpert-Ultrasound
      - ClosedMeditron/MedExpert-Xray
      - ClosedMeditron/clip-vit-base-patch32
    generalist_idx : -1
    gating_path: ClosedMeditron/MultiMeditron-Gating
    fusion_method: cross_attn
    top_k_experts: 5

training_mode: ALIGNMENT

datasets:
  - packed_path: /capstor/store/cscs/swissai/a127/meditron/multimediset/arrow/llava_pretrain_cleaned
  - packed_path: /capstor/store/cscs/swissai/a127/meditron/multimediset/arrow/pixmo_anything
  - packed_path: /capstor/store/cscs/swissai/a127/meditron/multimediset/arrow/pixmo_cap
  - packed_path: /capstor/store/cscs/swissai/a127/meditron/multimediset/arrow/medtrinity_conversations_1_formatted_alignment

training_args:
  output_dir: /capstor/store/cscs/swissai/a127/homes/meditron/models/multimeditron/freeze/attn_shared/MultiMeditron-8B-attn-shared-alignment
  run_name: MultiMeditron-8B-attn-shared-alignment
  dataloader_num_workers: 16
  dataloader_prefetch_factor: 4
  remove_unused_columns: false
  ddp_find_unused_parameters: false
  learning_rate: 1.0e-5
  bf16: true
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: true
  save_strategy: steps
  save_steps: 0.25
  max_grad_norm: 1.0
  deepspeed: ./config/deepspeed.json
  accelerator_config:
    dispatch_batches: false
  lr_scheduler_type: cosine_with_min_lr
  lr_scheduler_kwargs:
    min_lr: 1.0e-6
  report_to: wandb
  logging_steps: 1
  weight_decay: 0.01