name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker:
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: ubuntu-latest
            path: docker/Dockerfile
            tag_base: amd64
            name: multimeditron-git
          - platform: ubuntu-24.04-arm
            path: docker/Dockerfile
            tag_base: arm64
            name: multimeditron-git
          - platform: ubuntu-latest
            path: docker/Dockerfile.verl
            tag_base: amd64
            name: verl-multimeditron-git
          - platform: ubuntu-24.04-arm
            path: docker/Dockerfile.verl
            tag_base: arm64
            name: verl-multimeditron-git

    runs-on: ${{ matrix.platform }}
    environment: docker

    steps:
      - name: Move Docker storage to /mnt for more disk space
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo systemctl stop docker
          sudo rm -rf /var/lib/docker
          sudo mkdir /mnt/docker
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.path }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:latest-${{ matrix.tag_base }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ github.sha }}-${{ matrix.tag_base }}
